version: '3'

includes:
  run:
    taskfile: ~/.taskfilehub/hubs/run.yml
    vars:
      ContainerName: to-commonlisp
      ImageName: mooxe/apt_lisp

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  run-dev:
    cmds:
      - task: run:run-dev
        vars:
          run_option: '-v ~/.taskfilehub:/root/.taskfilehub'
